"""add inventory tracking

Revision ID: 2a5caccb6ad8
Revises: e2ab84ac72e6
Create Date: 2026-05-19 09:47:29.728451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5caccb6ad8'
down_revision = 'e2ab84ac72e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('change_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('before_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('after_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_qty', sa.Numeric(precision=12, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock_qty')

    op.drop_table('inventory_transactions')
    # ### end Alembic commands ###
