"""add_missing_customer_columns

Revision ID: 9add147b16f3
Revises: 2a5caccb6ad8
Create Date: 2026-05-20 12:09:53.807239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9add147b16f3'
down_revision = '2a5caccb6ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state_code', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('state_code')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
