"""
utils/pdf.py — WeasyPrint helper for generating PDF invoices.

Usage:
    from utils.pdf import html_to_pdf
    pdf_bytes = html_to_pdf(rendered_html)
"""

import io

try:
    from xhtml2pdf import pisa
    XHTML2PDF_AVAILABLE = True
except ImportError:
    XHTML2PDF_AVAILABLE = False


def html_to_pdf(html_string: str, base_url: str = None) -> bytes:
    """
    Convert an HTML string to PDF bytes using xhtml2pdf.

    Args:
        html_string: Complete HTML document as string.
        base_url:    Base URL for resolving relative paths (CSS, images).
                     If None, uses current working directory.

    Returns:
        PDF content as bytes.

    Raises:
        RuntimeError: If xhtml2pdf is not installed or PDF generation fails.
    """
    if not XHTML2PDF_AVAILABLE:
        raise RuntimeError(
            "xhtml2pdf is not installed. Run: pip install xhtml2pdf"
        )

    buf = io.BytesIO()
    # xhtml2pdf handles base paths via link_callback or simply parsing full URLs.
    # Passing the html_string directly should work for absolute URLs generated by Flask.
    pisa_status = pisa.CreatePDF(html_string, dest=buf)
    
    if pisa_status.err:
        raise RuntimeError("Failed to generate PDF via xhtml2pdf.")
        
    return buf.getvalue()
